### ISSUE TITLE
A question about the point in figure 1 in the paper

### ISSUE THREAD

**Issue by Maydaytyh** [nju-websoft/EPR-KGQA#1]
Thanks for your great work!
I found there is a point between Germany and Netherlands in Figure 1. This point has a relation "adjoin" with both Germany and Netherlands.
But I don't understand the meaning of this point as the Germany adjoins Netherlands directly.
Could you expain this?
Thank you
<img width="742" alt="image" src="https://github.com/nju-websoft/EPR-KGQA/assets/13815598/d9331d87-bfc6-4c4b-89a3-d1c5e2b32332">

**Comment by advAdder** [comment]
Sorry for the delayed response. Here is a CVT node in Freebase. CVTs in Freebase can be seen as facts of a multi-ary predicate. In the exported RDF format, they are expressed in a similar form as RDF blank nodes, which consist of several triples centered around an anonymous node that does not correspond to an actual entity. *In short, it expresses complex relationships using nodes rather than edges*. To ensure the generality of the method, our approach does not compress CVT expressions, thus resulting in situations like Figure 1.

I don't have access to a Freebase endpoint right now, so I can't help you look up the actual IRI corresponding to Figure 1. If I remember correctly, the CVT node here might be a `location.adjoining_relationship`.
